export const cvData = {
  personalInfo: {
    name: "Narek Kolyan",
    title: "Senior Frontend Engineer",
    email: "nqolyan@gmail.com",
    phone: "+37455818286",
    location: "Yerevan, Armenia",
    github: "https://github.com/narek941",
    linkedin: "https://linkedin.com/in/narek-qolyan-4a92b611b",
    bio: "Senior Frontend Engineer with 6+ years of experience building scalable web and mobile applications. Focused on React, TypeScript, architecture, and performance. Open to remote opportunities.",
    yearsOfExperience: "6+",
    specialization: "Frontend & Mobile Development",
  },
  professionalSummary:
    "Senior Frontend Engineer with 6+ years of experience building scalable web and mobile applications using React, TypeScript, and modern frontend architectures. Specialized in headless e-commerce, GraphQL data layers, and performance optimization for high-traffic applications. Experienced in modular UI systems, React Native, and delivering maintainable, scalable products.",
  keyEngineeringAchievements: [
    "achievement1",
    "achievement2",
    "achievement3",
    "achievement4",
    "achievement5",
    "achievement6",
  ],
  engineeringPrinciples: ["principle1", "principle2", "principle3"],
  skills: {
    frontend: [
      "React",
      "React Native",
      "TypeScript",
      "Redux",
      "Zustand",
      "React Query",
      "Context API",
      "Expo",
      "Next.js",
      "Vite",
      "React Hook Form",
      "SCSS/SASS",
      "Tailwind CSS",
    ],
    mobile: [
      "React Native + Expo",
      "iOS & Android Deployment",
      "BLE (Bluetooth Low Energy)",
      "HealthKit / Health Connect / Google Fit",
      "OTA Firmware Updates",
      "Push Notifications",
      "WebView",
      "Native Modules",
    ],
    backend: ["Node.js", "Express.js", "REST APIs", "GraphQL"],
    ecommerce: [
      "Shopify / Hydrogen",
      "Custom Checkout Flows",
      "Payment Gateways",
    ],
    tools: [
      "Git",
      "GitHub",
      "Jira",
      "Figma",
      "Postman",
      "Sentry",
      "Docker (basic)",
      "CI/CD",
    ],
    other: [
      "Responsive Design",
      "Performance Optimization",
      "GraphQL",
    ],
  },
  experience: [
    {
      company: "ShellLogix",
      companyDescription:
        "Outsource-based software company specializing in web and mobile-based work management, project management, and custom digital solutions.",
      companyUrl: "https://shelllogix.com/",
      position: "Senior Frontend Engineer",
      period: "Oct 2021 – Present",
      location: "Yerevan, Armenia",
      description: [
        "Worked on various client projects as part of an outsource team, developing web and mobile applications using React, React Native, and TypeScript",
        "Collaborated with international clients and teams to deliver high-quality software solutions",
        "Built responsive web applications and cross-platform mobile apps with modern state management and secure authentication",
        "Contributed to multiple projects including e-commerce platforms, business management tools, and financial applications",
      ],
    },
    {
      company: "Opta Sports (by Stats Perform)",
      companyDescription:
        "World leader in sports AI. With 7.2 petabytes of proprietary sports data and 8 foundation sports AI models, empowering the world's top sports broadcasters, media, apps, leagues, federations, bookmakers and teams.",
      companyUrl: "https://www.statsperform.com/",
      position: "Data Researcher / Editor",
      period: "Nov 2016 – Mar 2025",
      location: "Yerevan / Remote",
      description: [
        "Managed, validated, and edited large-scale sports datasets across multiple leagues with 100% accuracy and strict deadlines",
        "Coordinated with global data teams to deliver real-time statistics to broadcasters, media partners, and betting companies",
        "Strong domain knowledge in sports data helped significantly in building accurate filtering and statistics-heavy UIs",
      ],
    },
  ],
  education: [
    {
      institution: "Armenian National Agrarian University",
      degree: "Bachelor's Degree in Agriculture Marketing & Business",
      period: "Sep 2018 – Jun 2022",
      location: "Yerevan, Armenia",
      note: "Relevant coursework: Economics, Statistics, Project Management",
    },
  ],
  languages: [
    { name: "Armenian", level: "Native / First Language" },
    { name: "Russian", level: "C1 – Advanced" },
    {
      name: "English",
      level: "B2 – Upper-Intermediate (professional working proficiency)",
    },
  ],
  additionalInfo: [
    "Available for full-time remote or relocation (EU, USA, Canada preferred)",
    "Passionate about clean code, performance, and beautiful UI/UX",
    "Active open-source contributor on GitHub",
    "Fast learner – successfully transitioned from sports data industry to full-time software engineering",
  ],
};
