import type { Project } from "@/types/projects.types";

export const projects: Project[] = [
  {
    id: "accounting-platform",
    name: "Accounting Company Website",
    description:
      "My first project - still in use today. Multi-language web application for accounting services in Armenia. Features canvas forms and form-to-email functionality. Built with modern React stack.",
    technologies: [
      "Next.js",
      "React",
      "Redux",
      "SCSS",
      "Canvas API",
      "Email Integration",
    ],
    features: [
      "Multi-language support (Armenian, English, Russian)",
      "Canvas-based form generation",
      "Form-to-email functionality",
      "Company registration services",
      "Tax planning and consultation",
      "Responsive design for all devices",
    ],
    status: "production",
    type: "web",
    teamProject: false,
  },
  {
    id: "crypto-admin-panel",
    name: "Cryptocurrency Admin Panel",
    description:
      "Admin panel for cryptocurrency exchange and statistics. Built for a Ukrainian company. Features real-time crypto exchange rates, trading statistics, and comprehensive admin dashboard. Frontend development only.",
    technologies: [
      "React",
      "TypeScript",
      "Redux",
      "WebSocket",
      "Chart.js",
      "Admin Dashboard",
    ],
    features: [
      "Real-time cryptocurrency exchange rates",
      "Trading statistics and analytics",
      "Admin dashboard interface",
      "Data visualization with charts",
      "User management system",
    ],
    status: "production",
    type: "web",
    teamProject: false,
  },
  {
    id: "mobile-ecommerce-solution",
    name: "Mobile E-commerce Solution",
    description:
      "Russian company providing ready-to-use mobile shopping applications for 100+ brands from Russia, UK, and US. Solutions for various industries from pharmacy to automobile. Features 5+ analytics variants, custom backend, Shopify backend integration. Worked as fullstack developer (React, React Native, Node.js) with 40+ team members.",
    technologies: [
      "React Native",
      "React",
      "TypeScript",
      "Node.js",
      "Express",
      "Shopify API",
      "Analytics",
      "Push Notifications",
    ],
    features: [
      "Ready-to-use applications for 100+ brands",
      "Multiple analytics variants (5+)",
      "Custom backend integration",
      "Shopify backend support",
      "Cross-platform (iOS & Android)",
      "Industry-specific solutions",
      "Real-time product browsing",
      "Secure checkout and payments",
    ],
    status: "production",
    type: "mobile",
    teamProject: true,
  },
  {
    id: "rv-rental-platform",
    name: "RV Rental Platform",
    description:
      "US-based company project for RV rental services. Custom Shopify solution allowing clients to rent RV vehicles and book campgrounds. Worked as React developer on multiple RV rental related projects.",
    technologies: [
      "Shopify",
      "React",
      "TypeScript",
      "Custom Checkout",
      "Booking System",
      "Payment Integration",
    ],
    features: [
      "RV vehicle rental system",
      "Campground booking functionality",
      "Custom Shopify checkout",
      "Payment processing",
      "Reservation management",
      "Multi-project involvement",
    ],
    status: "production",
    type: "web",
    teamProject: true,
  },
  {
    id: "ai-social-media-generator",
    name: "AI Social Media Post Generator",
    description:
      "Business tool for generating social media posts using multiple AI models. Generates videos by parts and seamlessly connects them together. Automates content creation workflow for businesses. Built for US client.",
    technologies: [
      "React",
      "TypeScript",
      "AI Integration",
      "Video Processing",
      "API Integration",
    ],
    features: [
      "Multiple AI model integration",
      "Video generation by parts",
      "Automatic video connection",
      "Social media post creation",
      "Content automation workflow",
      "Business-focused features",
    ],
    status: "production",
    type: "web",
    teamProject: false,
  },
  {
    id: "git-cli-tool",
    name: "Git Identity Management CLI",
    description:
      "npm package for managing multiple Git identities. Easily switch between work, personal, and organization accounts with cross-platform support. Personal open-source project.",
    technologies: [
      "TypeScript",
      "Node.js",
      "Commander.js",
      "Jest",
      "Shell Scripting",
    ],
    features: [
      "Cross-platform support",
      "Interactive CLI setup",
      "Automatic SSH key switching",
      "Shell integration",
      "50+ unit tests",
    ],
    npm: "https://www.npmjs.com/package/use-multiple-gits",
    status: "published",
    type: "cli",
    teamProject: false,
  },
  {
    id: "service-admin-panel",
    name: "Service Admin Panel",
    description:
      "Russian company based in Cyprus with 50+ employees. Enterprise admin dashboard for user segmentation and marketing campaigns. Features real-time analytics, advanced filtering, and integrations with HubSpot and Communication Service.",
    technologies: [
      "React 19",
      "TypeScript",
      "Vite",
      "Ant Design",
      "React Query",
      "Zustand",
    ],
    features: [
      "Real-time dashboard analytics",
      "User segmentation management",
      "Advanced filtering system",
      "HubSpot integration",
      "Communication Service sync",
      "Feature-based architecture",
    ],
    status: "production",
    type: "web",
    teamProject: true,
  },
  {
    id: "mobile-webview-app",
    name: "Mobile WebView Application",
    description:
      "React Native application with WebView integration for displaying company website. Main feature is per-app VPN functionality that users can enable directly in the app. Built for previous company.",
    technologies: [
      "React Native",
      "TypeScript",
      "WebView",
      "Per-App VPN",
      "Native Modules",
    ],
    features: [
      "WebView component integration",
      "Per-app VPN functionality",
      "In-app VPN toggle",
      "Cross-platform support (Android & iOS)",
      "Native module integration",
    ],
    status: "production",
    type: "mobile",
    teamProject: true,
  },
];
