import type { Project } from "@/entities/project/projects.types";

export const projects: Project[] = [
  {
    id: "accounting-platform",
    name: "Accounting Company Website",
    description:
      "My first project - still in use today. Multi-language web application for accounting services in Armenia. Features canvas forms and form-to-email functionality. Built with modern React stack.",
    technologies: [
      "Next.js",
      "React",
      "Redux",
      "SCSS",
      "Canvas API",
      "Email Integration",
    ],
    features: [
      "Multi-language support (Armenian, English, Russian)",
      "Canvas-based form generation",
      "Form-to-email functionality",
      "Company registration services",
      "Tax planning and consultation",
      "Responsive design for all devices",
    ],
    github: "https://github.com/narek941/accountant",
    link: "https://accountant-front-v2-alpha.vercel.app",
    status: "production",
    type: "web",
    teamProject: false,
  },
  {
    id: "armapply-telegram-bot",
    name: "AI Job Hunter Bot",
    description:
      "Telegram-first AI job hunter. Upload a CV once, discover jobs daily, score fit with an LLM, and create grounded Gmail drafts with one tap — sent from the user's own account.",
    technologies: [
      "Python",
      "FastAPI",
      "PostgreSQL",
      "Gemini",
      "Gmail API",
      "Telegram Bot API",
    ],
    features: [
      "CV upload with LLM profile parsing (pdfplumber + OCR fallback)",
      "Daily job discovery from LinkedIn, staff.am, and Telegram channels",
      "Fit scoring with grounded, experience-based cover letters",
      "One-tap Gmail draft creation with CV attached",
      "User-owned Gmail sending — no shared inbox spam",
      "Per-user Postgres state indexed by Telegram chat ID",
    ],
    github: "https://github.com/narek941/job-be",
    status: "development",
    type: "cli",
    teamProject: false,
  },
  {
    id: "crypto-admin-panel",
    name: "Cryptocurrency Admin Panel",
    description:
      "Admin panel for cryptocurrency exchange and statistics. Built for a Ukrainian company. Real-time pair tickers, account analytics with capital charts, trading tables, and role-based admin navigation. Frontend development only.",
    technologies: [
      "React",
      "TypeScript",
      "Redux Toolkit",
      "Chart.js",
      "React Router",
      "SCSS",
    ],
    features: [
      "Real-time cryptocurrency exchange rates",
      "Account capital and P&L analytics with area charts",
      "Trading pairs and assets doughnut breakdowns",
      "Accounts, users, and alerts management",
      "Export and multi-exchange account overview",
    ],
    github: "https://github.com/narek941/Crypto",
    status: "production",
    type: "web",
    teamProject: false,
  },
  {
    id: "nft-whitelabel-platform",
    name: "NFT White Label Platform",
    description:
      "White-label NFT marketplace front-end. Next.js platform with pack drops, collections, redeem flows, wallet connect, and Redux Toolkit entity architecture with Storybook components.",
    technologies: [
      "Next.js",
      "TypeScript",
      "Redux Toolkit",
      "SCSS",
      "Storybook",
      "Axios",
    ],
    features: [
      "White-label NFT marketplace with themed color packs",
      "Pack carousel, collection filters, and redeem flows",
      "Wallet connect and shopping cart integration",
      "Entity-driven Redux architecture with mock/API injection",
      "Component library documented in Storybook",
      "Responsive layouts with Poppins design system",
    ],
    github: "https://github.com/narek941/NFT",
    status: "production",
    type: "web",
    teamProject: true,
  },
  {
    id: "mobile-ecommerce-solution",
    name: "Mobile E-commerce Solution",
    architectureHighlightKeys: ["arch1", "arch2", "arch3"],
    description:
      "Russian company providing ready-to-use mobile shopping applications for 100+ brands from Russia, UK, and US. Solutions for various industries from pharmacy to automobile. Features 5+ analytics variants, custom backend, Shopify backend integration. Worked as fullstack developer (React, React Native, Node.js) with 40+ team members.",
    technologies: [
      "React Native",
      "React",
      "TypeScript",
      "Node.js",
      "Express",
      "Shopify API",
      "Analytics",
      "Push Notifications",
    ],
    features: [
      "Ready-to-use applications for 100+ brands",
      "Multiple analytics variants (5+)",
      "Custom backend integration",
      "Shopify backend support",
      "Cross-platform (iOS & Android)",
      "Industry-specific solutions",
      "Real-time product browsing",
      "Secure checkout and payments",
    ],
    status: "production",
    type: "mobile",
    teamProject: true,
  },
  {
    id: "rv-rental-platform",
    name: "RV Rental Platform",
    architectureHighlightKeys: ["arch1", "arch2", "arch3"],
    description:
      "US-based company project for RV rental services. Custom Shopify solution allowing clients to rent RV vehicles and book campgrounds. Worked as React developer on multiple RV rental related projects.",
    technologies: [
      "Shopify",
      "React",
      "TypeScript",
      "Custom Checkout",
      "Booking System",
      "Payment Integration",
    ],
    features: [
      "RV vehicle rental system",
      "Campground booking functionality",
      "Custom Shopify checkout",
      "Payment processing",
      "Reservation management",
      "Multi-project involvement",
    ],
    status: "production",
    type: "web",
    teamProject: true,
  },
  {
    id: "ai-social-media-generator",
    name: "AI Social Media Post Generator",
    architectureHighlightKeys: ["arch1", "arch2", "arch3"],
    description:
      "Business studio for AI social content. Multi-model image and video generation (Leonardo, Veo 3), scene-based video stitching, brand guideline validation, and automated prompt pipelines. Built for US client.",
    technologies: [
      "React",
      "TypeScript",
      "Vite",
      "Supabase",
      "OpenRouter",
      "TanStack Query",
    ],
    features: [
      "Multiple AI model integration",
      "Video generation by parts",
      "Automatic video connection",
      "Social media post creation",
      "Content automation workflow",
      "Business-focused features",
    ],
    status: "production",
    type: "web",
    teamProject: false,
  },
  {
    id: "git-cli-tool",
    name: "Git Identity Management CLI",
    description:
      "npm package for managing multiple Git identities. Easily switch between work, personal, and organization accounts with cross-platform support. Personal open-source project.",
    technologies: [
      "TypeScript",
      "Node.js",
      "Commander.js",
      "Jest",
      "Shell Scripting",
    ],
    features: [
      "Cross-platform support",
      "Interactive CLI setup",
      "Automatic SSH key switching",
      "Shell integration",
      "50+ unit tests",
    ],
    github: "https://github.com/narek941/use-multiple-gits",
    npm: "https://www.npmjs.com/package/use-multiple-gits",
    status: "published",
    type: "cli",
    teamProject: false,
  },
  {
    id: "dealer-service-portal",
    name: "Dealer Service Portal",
    description:
      "Nx monorepo for cabinetry manufacturing — admin analytics dashboard, dealer account management, quote workflows, and role-based portals for internal staff and dealer partners.",
    technologies: [
      "Nx",
      "React",
      "TanStack Router",
      "Ant Design",
      "Prisma",
      "TypeScript",
    ],
    features: [
      "Admin analytics with period filters (7d / 30d / 90d / YTD)",
      "Dealer account management and status workflows",
      "Role-based admin and dealer client apps",
      "Quote pipeline KPIs and dealer rankings",
      "Organizations and users tables with live filtering",
      "Feature-based Nx workspace architecture",
    ],
    status: "production",
    type: "web",
    teamProject: true,
  },
  {
    id: "service-admin-panel",
    name: "Service Admin Panel",
    architectureHighlightKeys: ["arch1", "arch2", "arch3"],
    description:
      "Russian company based in Cyprus with 50+ employees. Enterprise admin dashboard for user segmentation and marketing campaigns. Features real-time analytics, advanced filtering, and integrations with HubSpot and Communication Service.",
    technologies: [
      "React 19",
      "TypeScript",
      "Vite",
      "Ant Design",
      "React Query",
      "Zustand",
    ],
    features: [
      "Real-time dashboard analytics",
      "User segmentation management",
      "Advanced filtering system",
      "HubSpot integration",
      "Communication Service sync",
      "Feature-based architecture",
    ],
    status: "production",
    type: "web",
    teamProject: true,
  },
  {
    id: "mobile-webview-app",
    name: "Mobile WebView Application",
    description:
      "React Native application with WebView integration for displaying company website. Main feature is per-app VPN functionality that users can enable directly in the app. Built for previous company.",
    technologies: [
      "React Native",
      "TypeScript",
      "WebView",
      "Per-App VPN",
      "Native Modules",
    ],
    features: [
      "WebView component integration",
      "Per-app VPN functionality",
      "In-app VPN toggle",
      "Cross-platform support (Android & iOS)",
      "Native module integration",
    ],
    status: "production",
    type: "mobile",
    teamProject: true,
  },
  {
    id: "mobile-health-device-app",
    name: "Smart Device & Health Mobile App",
    description:
      "Cross-platform mobile app for connected smart devices and health data. BLE device pairing, OTA firmware updates, and sync with major health platforms. React Native with TypeScript and Expo.",
    technologies: [
      "React Native",
      "TypeScript",
      "Expo",
      "BLE",
      "HealthKit",
      "Health Connect",
      "Google Fit",
      "OTA Firmware",
    ],
    features: [
      "BLE device connectivity and pairing",
      "Over-the-air firmware updates",
      "Health platform sync (iOS HealthKit, Android Health Connect, Google Fit)",
      "Stats dashboard and progress tracking",
      "Cross-platform (iOS & Android)",
      "Native module integration",
    ],
    status: "production",
    type: "mobile",
    teamProject: true,
  },
];
